name: build

on:
  workflow_dispatch:
  # schedule:
  #   # * is a special character in YAML so you have to quote this string
  #   - cron:  '0 12 * * *'
  # push:
  #   branches:
  #     - main
env:
  GH_REGISTRY: ghcr.io
  GH_IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
    - uses: actions/checkout@v3
    - name: Login to docker registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_REGISTRY_USER }}
        password: ${{ secrets.DOCKERHUB_REGISTRY_PASSWORD }}
    - name: Log in to the github registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.GH_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Fetch lego release version
      run: |
        curl -sL https://api.github.com/repos/go-acme/lego/releases/latest | \
        jq -r ".tag_name" > latestversion.txt
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: all
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: latest
    - name: Build Image
      run: |
        version=$(cat latestversion.txt) \
        && docker buildx build \
        --platform linux/amd64,linux/arm/v7,linux/arm64 \
        --output "type=image,push=true" \
        --build-arg VERSION=$version \
        --tag brahmadev/acme-lego-cron:$version \
        --tag ghcr.io/brahma-dev/acme-lego-cron:$version \
        --tag brahmadev/acme-lego-cron:latest \
        --tag ghcr.io/brahma-dev/acme-lego-cron:latest .
    - name: Clean-up
      run: rm -f ${HOME}/.docker/config.json
      if: always()
